/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,js,ts}','./projects/**/*.{html,ts}'],
  safelist: [
    'bg-purple-200',
    'bg-green-600',
    'bg-rose-600',
    'divide-solid',
    'divide-y',
    'float-start',
    'float-end',
    'float-right',
    'float-left',
    'float-none',
    'flex',
    'flex-col',
    'font-bold',
    'font-light',
    'h-7',
    'h-[200px]',
    'h-[260px]',
    'h-full',
    'items-center',
    'justify-between',
    'mat-elevation-z8',
    'mb-1',
    'mb-2',
    'mx-5',
    'mx-auto',
    'p-3',
    'pt-3',
    'px-24',
    'px-8',
    'py-3',
    'rounded-full',
    'text-center',
    'text-gray-500',
    'text-green-400',
    'text-red-400',
    'text-white',
    'truncate',
    'w-64',
    'w-7',
    'w-full',
],
  theme: {
    extend: {
      backgroundColor: {
        'secondary': '#96180f',
      }
    },
  },
  plugins: [],
}

